# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_02',
                'doc_host': 'https://ATSpuler.github.io',
                'git_url': 'https://github.com/ATSpuler/nbdev_02',
                'lib_path': 'nbdev_02'},
  'syms': {'nbdev_02.core': {'nbdev_02.core.foo': ('core.html#foo', 'nbdev_02/core.py')}}}
